package com.abelhzo.jwt.entities;
// Generated Sep 5, 2023, 6:39:59 PM by Hibernate Tools 6.2.4.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Timestamp;

/**
 * UserRol generated by hbm2java
 */
@Entity
@Table(name = "USERS_ROLES", schema = "PUBLIC", catalog = "JWTDB")
public class UserRol implements java.io.Serializable {

	private static final long serialVersionUID = -1409343949009195398L;
	private Long idUserRol;
	private User user;
	private Rol rol;
	private Timestamp created;

	public UserRol() {
	}

	public UserRol(Long idUserRol, User user, Rol rol, Timestamp created) {
		this.idUserRol = idUserRol;
		this.user = user;
		this.rol = rol;
		this.created = created;
	}

	@Id
	@Column(name = "ID_USER_ROL", unique = true, nullable = false)
	public Long getIdUserRol() {
		return this.idUserRol;
	}

	public void setIdUserRol(Long idUserRol) {
		this.idUserRol = idUserRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_USER", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ROL", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED", nullable = false, length = 26)
	public Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(Timestamp created) {
		this.created = created;
	}

}
